apiVersion: v1
kind: Service
metadata:
  name: ssh-service
spec:
  type: ClusterIP
  selector:
    component: ssh-example
  ports:
  - name: ssh-open
    port: 9022
    targetPort: 22
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9433